#!/bin/bash
set -euo pipefail

INPLACE=false
if [[ "${1:-}" == "-i" ]]; then
  INPLACE=true
  shift
fi

if [[ $# -ne 1 ]]; then
  echo "Usage: muon-format [-i] <file>" >&2
  exit 1
fi

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
FILE="$1"
TEMP=$(mktemp)
trap 'rm -f "$TEMP" "$TEMP.out"' EXIT

# Step 1: Replace __attribute__((...)) at start of line with /**/ [[muon::sentinel(...)]]
sed -E 's/^([[:space:]]*)__attribute__\(\(([^)]*)\)\)/\1\/**\/ [[muon::sentinel(\2)]]/g' "$FILE" > "$TEMP"

# Step 2: Prepend /**/ to attribute macros at start of line
MUON_ATTR='MUON_CONST|MUON_COUNTED_BY|MUON_FORMAT|MUON_MALLOC|MUON_NONNULL_ARGS|MUON_NONNULL|MUON_PURE|MUON_RETURNS_NONNULL'
sed -E "s/^([[:space:]]*)(${MUON_ATTR})/\1\/**\/ \2/g" "$TEMP" > "$TEMP.out"
mv "$TEMP.out" "$TEMP"

# Step 3: Run clang-format
CLANG_FORMAT="docker run --rm -i -v $ROOT:/work muon-clang-format"
# Use .c extension for --assume-filename so clang-format detects C, not ObjC
$CLANG_FORMAT --style=file --assume-filename="${FILE%.h}.c" < "$TEMP" > "$TEMP.out"
mv "$TEMP.out" "$TEMP"

# Step 4: Dedent "  /**/" to "/**/"
sed -E 's/^([[:space:]]*)  \/\*\*\//\1\/**\//' "$TEMP" > "$TEMP.out"
mv "$TEMP.out" "$TEMP"

# Step 5: Remove /**/ prefix from attribute macros and [[muon::sentinel(...)]]
sed -E "s/\/\*\*\/ (${MUON_ATTR})/\1/g" "$TEMP" > "$TEMP.out"
mv "$TEMP.out" "$TEMP"
sed -E 's/\/\*\*\/ \[\[muon::sentinel\(([^)]*)\)\]\]/__attribute__((\1))/g' "$TEMP" > "$TEMP.out"
mv "$TEMP.out" "$TEMP"

if [[ "$INPLACE" == true ]]; then
  cp "$TEMP" "$FILE"
else
  cat "$TEMP"
fi
